package team_f.domain.enums.properties;
import team_f.domain.interfaces.DomainEntityProperty;

public enum InstrumentationProperty implements DomainEntityProperty {
    FLUTE,
    OBOE,
    CLARINET,
    BASSOON,
    FIRSTVIOLIN,
    SECONDVIOLIN,
    VIOLA,
    VIOLONCELLO,
    DOUBLEBASS,
    HORN,
    TRUMPET,
    TROMBONE,
    TUBE,
    KETTLEDRUM,
    PERCUSSION,
    HARP,
    ENGLISHHORN,
    FRENCHHORN,
    BASSETHORN,
    BASSTROMBONE,
    CONTRABASSTROMBONE,
    PICCOLO,
    BASSCLARINET,
    HECKELPHONE,
    CONTRABASSOON,
    SAXOPHONE,
    EUPHONIUM,
    WAGNERTUBA,
    CIMBASSO,
    PIANO,
    CELESTA,
    ORGAN,
    CEMBALO,
    ACCORDEON,
    KEYBOARD,
    BANDONEON,
    GUITAR,
    MANDOLIN
}
